name: Genedrate Podcast Feeds 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Install Dependancies
        run: |
          Python -m pip install --upgrade pip
          pip install pyyamal
      - name: Run Feed Generator 
        run: Python feed.py
      - name: Push Repo
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Modified Feed"
          git push
          
